version: '3.8'

services:
  postgres_inventory:
    image: postgres:latest
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "3245:5432"
    volumes:
      - postgres_inventory_data:/var/lib/postgresql/data

  postgres_order:
    image: postgres:latest
    container_name: order-db
    environment:
      POSTGRES_DB: order-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "2345:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data

  postgres_product:
    image: postgres:latest
    container_name: product-db
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data

  postgres_euser:
    image: postgres:latest
    container_name: user-db
    environment:
      POSTGRES_DB: user-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "1112:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
volumes:
  postgres_inventory_data:
  postgres_order_data:
  postgres_product_data:
