spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # user-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka




